In [1]:
import numpy as np

np_arr = np.array([[0, 1, 2, 3], [2, 4, -1, 0], [0, 0, 3, 4]])
np_arr.shape

(3, 4)

In [2]:
arr_meaned = np_arr - np.mean(np_arr , axis = 0)
arr_meaned

array([[-0.66666667, -0.66666667,  0.66666667,  0.66666667],
       [ 1.33333333,  2.33333333, -2.33333333, -2.33333333],
       [-0.66666667, -1.66666667,  1.66666667,  1.66666667]])

In [3]:
cov_mat = np.cov(arr_meaned, rowvar=False)
cov_mat

array([[ 1.33333333,  2.33333333, -2.33333333, -2.33333333],
       [ 2.33333333,  4.33333333, -4.33333333, -4.33333333],
       [-2.33333333, -4.33333333,  4.33333333,  4.33333333],
       [-2.33333333, -4.33333333,  4.33333333,  4.33333333]])

In [4]:
u, s, v = np.linalg.svd(cov_mat)

In [5]:
u

array([[-2.98332921e-01,  9.54461874e-01,  5.06676037e-15,
        -7.29030269e-17],
       [-5.51058820e-01, -1.72242592e-01,  4.08248290e-01,
         7.07106781e-01],
       [ 5.51058820e-01,  1.72242592e-01, -4.08248290e-01,
         7.07106781e-01],
       [ 5.51058820e-01,  1.72242592e-01,  8.16496581e-01,
        -3.30023329e-15]])

In [6]:
u.shape

(4, 4)

In [7]:
s

array([1.42632230e+01, 7.01103813e-02, 1.13311663e-17, 5.56273309e-32])

In [8]:
s[:1].sum() / s.sum() * 100

99.51085780475294

In [9]:
k = 2
u_subset = u[:, :k]
u_subset

array([[-0.29833292,  0.95446187],
       [-0.55105882, -0.17224259],
       [ 0.55105882,  0.17224259],
       [ 0.55105882,  0.17224259]])

In [10]:
arr_reduced = np.dot(arr_meaned, u_subset)
arr_reduced

array([[ 1.30100625, -0.29182273],
       [-4.25518897,  0.06691769],
       [ 2.95418271,  0.22490505]])

In [11]:
np_arr

array([[ 0,  1,  2,  3],
       [ 2,  4, -1,  0],
       [ 0,  0,  3,  4]])

In [12]:
def MyPCA(X, num_components):
    arr_meaned = X - np.mean(X, axis=0)
    cov_mat = np.cov(arr_meaned, rowvar=False)
    u, s, v = np.linalg.svd(cov_mat)
    u_subset = u[:, :num_components]
    arr_reduced = np.dot(arr_meaned, u_subset)
    return arr_reduced

In [13]:
MyPCA(np_arr, 2)

array([[ 1.30100625, -0.29182273],
       [-4.25518897,  0.06691769],
       [ 2.95418271,  0.22490505]])

In [14]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 2)
arr_reduced = pca.fit_transform(np_arr)
arr_reduced

array([[-1.30100625,  0.29182273],
       [ 4.25518897, -0.06691769],
       [-2.95418271, -0.22490505]])