In [9]:
import numpy as np

np_arr = np.array([[0, 1, 2, 3], [2, 4, -1, 0], [0, 0, 3, 4]])
np_arr.shape

(3, 4)

In [10]:
arr_meaned = np_arr - np.mean(np_arr , axis = 0)
arr_meaned

array([[-0.66666667, -0.66666667,  0.66666667,  0.66666667],
       [ 1.33333333,  2.33333333, -2.33333333, -2.33333333],
       [-0.66666667, -1.66666667,  1.66666667,  1.66666667]])

In [11]:
cov_mat = np.cov(arr_meaned, rowvar=False)
cov_mat

array([[ 1.33333333,  2.33333333, -2.33333333, -2.33333333],
       [ 2.33333333,  4.33333333, -4.33333333, -4.33333333],
       [-2.33333333, -4.33333333,  4.33333333,  4.33333333],
       [-2.33333333, -4.33333333,  4.33333333,  4.33333333]])

In [12]:
u, s, v = np.linalg.svd(cov_mat)

In [13]:
for vector in u : 
    for elem in vector : 
        print("{:.2f}".format(elem), end=' ')
    print()

-0.30 0.95 0.00 -0.00 
-0.55 -0.17 0.41 0.71 
0.55 0.17 -0.41 0.71 
0.55 0.17 0.82 -0.00 


In [14]:
u.shape

(4, 4)

In [15]:
s

array([1.42632230e+01, 7.01103813e-02, 1.13311663e-17, 5.56273309e-32])

In [18]:
s[:1].sum() / s.sum() * 100

99.51085780475294

In [19]:
k = 2
u_subset = u[:, :k]
u_subset

array([[-0.29833292,  0.95446187],
       [-0.55105882, -0.17224259],
       [ 0.55105882,  0.17224259],
       [ 0.55105882,  0.17224259]])

In [20]:
arr_reduced = np.dot(arr_meaned, u_subset)
arr_reduced

array([[ 1.30100625, -0.29182273],
       [-4.25518897,  0.06691769],
       [ 2.95418271,  0.22490505]])

In [11]:
np_arr

array([[ 0,  1,  2,  3],
       [ 2,  4, -1,  0],
       [ 0,  0,  3,  4]])

In [21]:
def MyPCA(X, num_components):
    arr_meaned = X - np.mean(X, axis=0)
    cov_mat = np.cov(arr_meaned, rowvar=False)
    u, s, v = np.linalg.svd(cov_mat)
    u_subset = u[:, :num_components]
    arr_reduced = np.dot(arr_meaned, u_subset)
    return arr_reduced

In [22]:
MyPCA(np_arr, 2)

array([[ 1.30100625, -0.29182273],
       [-4.25518897,  0.06691769],
       [ 2.95418271,  0.22490505]])

In [14]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 2)
arr_reduced = pca.fit_transform(np_arr)
arr_reduced

array([[-1.30100625,  0.29182273],
       [ 4.25518897, -0.06691769],
       [-2.95418271, -0.22490505]])